### ISSUE TITLE
 TSP_REPLY Digest must also go over the VID's of the envelope

### ISSUE THREAD

**Issue by marlonbaeten** [openwallet-foundation-labs/tsp#9]
Currently only the payload is hashed.

**Comment by tweedegolf-marc** [comment]
Note that in the earlier spec, the digest was computed over the payload-before-encryption. This causes it to be unknown to outside parties (which feels like it's a good thing, since a thread-id seems to act like a "cookie" for relationships, and knowledge of a thread-id also demonstrates possession of a private key).

In the current implementors draft it seems to just go over the publically visible message; I'm not sure what benefit that conveys. (Implementation-wise, it also has the a slight performance downside that it might force us to always compute a hash over every input -- of course compared to the other crypto going on that is negligible)
